title: __TITLE__
author: "ElderLab"
copyright: "ElderLab"
logo: "https://www.elderlab.yorku.ca/wp-content/uploads/2017/10/Artboard-10@2x.png"

execute:
  execute_notebooks: off
  
launch_buttons:
  notebook_interface: jupyterlab
  colab_url: https://colab.research.google.com
  binderhub_url: https://mybinder.org
  
repository:
  url: __REPOSITORY_URL__
  path_to_book: ./
  branch: booklet
  
html:
  google_analytics_id: __G_ANALYTICS_ID__
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
